include:
  - project: pagekey/libs/cicd
    ref: main
    file: 01-version/semantic-release.yaml
  - project: pagekey/libs/cicd
    ref: main
    file: 03-docs/docgen.yaml

stages:
  - version
  - test
  - docs
  - build
  - publish
